version: 2

sources:
  - name: raw_data_circle
    description: raw data circle (sportswear) for le wagon project.
    tables:
      - name: raw_cc_stock
        description: stocks
      - name: raw_cc_sales
        description: sales data!

models:
  - name: stg_raw_data_circle__raw_cc_sales
    description: sales model
  - name: stg_raw_data_circle__raw_cc_stocks
    description: stocks
  - name: int_stock_sales
    description: joined version of sales and stocks models

